"""
app/models/resume.py — Resume table.

Stores both the base (originally uploaded) resume and any tailored versions
generated by the pipeline.  Each tailored version is linked to a user and
carries a version number so history is preserved.
"""

from datetime import datetime, timezone

from sqlalchemy import Boolean, DateTime, ForeignKey, Index, Integer, Text, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


class Resume(Base):
    __tablename__ = "resumes"
    __table_args__ = (
        Index("ix_resumes_user_is_base_version", "user_id", "is_base", "version"),
    )

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)

    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )

    # Monotonically increasing per user — base resume is typically version 1
    version: Mapped[int] = mapped_column(Integer, nullable=False, default=1)

    # Plain text extracted from the uploaded PDF/DOCX
    source_text: Mapped[str] = mapped_column(Text, nullable=False)

    # Original uploaded file name, so the UI can show the saved resume by name.
    filename: Mapped[str | None] = mapped_column(String(255), nullable=True)

    # Normalized HTML that preserves the original layout/section structure.
    # The tailor_resume LangGraph node fills gaps into this template.
    source_html: Mapped[str | None] = mapped_column(Text, nullable=True)

    # True for the originally uploaded resume; False for tailored versions
    is_base: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )

    # ── Relationships ──────────────────────────────────────────────────────────
    user: Mapped["User"] = relationship("User", back_populates="resumes")  # noqa: F821
    applications: Mapped[list["Application"]] = relationship(  # noqa: F821
        "Application", back_populates="resume"
    )

    def __repr__(self) -> str:
        return f"<Resume id={self.id} user_id={self.user_id} version={self.version} is_base={self.is_base}>"
